const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const defaults={name:'Surya',language:'en',theme:'evergreen',reminders:true,onboarded:false};
let prefs={...defaults,...JSON.parse(localStorage.getItem('haven-preferences')||'{}')};
let tasks=JSON.parse(localStorage.getItem('haven-tasks')||'null')||[
 {name:'Renew car insurance',meta:'Due in 8 days · Insurance',tag:'Important',urgent:true},
 {name:'Schedule a dental check-up',meta:'This week · Health',tag:'This week'},
 {name:'Review your Netflix plan',meta:'Renews 19 Jul · Subscription',tag:'Quick win'},
 {name:'Book AC service',meta:'Before monsoon season · Home',tag:'Home'},
 {name:'Update emergency contacts',meta:'No due date · Personal',tag:'Personal',done:true},
 {name:'File electricity receipt',meta:'Completed · Documents',tag:'Done',done:true}
];
const timeline=[['TODAY','Pay electricity bill','₹1,860 · Auto-pay'],['16 JUL','Dental check-up','11:30 AM · Dr. Mehta'],['19 JUL','Netflix renewal','₹649 · Subscription'],['20 JUL','Car insurance','Review & renew','urgent']];
const bills=[['⚡','Tata Power','Due today','₹1,860'],['N','Netflix','19 Jul · Auto-pay','₹649'],['◉','JioFiber','23 Jul · Auto-pay','₹999'],['⌂','Apartment maintenance','01 Aug','₹6,500']];
const docs=[['⌑','Car insurance','Policy #IC-7429 · Expires 20 Jul 2026','Renewal due soon'],['▤','Phone warranty','iPhone 15 · Valid until 14 Sep 2026','Protected'],['⌂','Rental agreement','Bangalore apartment · Ends 31 Mar 2027','Saved'],['✚','Health insurance','Policy #H-2281 · Renews 10 Jan 2027','Protected'],['▤','Vehicle RC','KA 01 MN 4821 · Updated 12 Jun 2026','Saved'],['⌑','Passport copy','Expires 14 Nov 2030','Saved']];
const home=[['❄','Air conditioner','Last serviced 10 months ago','Book a service'],['◉','Car — Honda City','Insurance renewal in 8 days','Review insurance'],['▣','Water purifier','Filter change due in August','Set reminder'],['▤','iPhone 15','Warranty valid for 64 more days','View warranty'],['⌂','Apartment','Maintenance due 01 Aug','View payment'],['⌁','Gas connection','Annual inspection in November','Set reminder']];
const translations={en:{overview:'Overview',tasks:'Tasks',money:'Money',documents:'Documents',home:'Home & things',settings:'Settings',greet:'Good morning'},hi:{overview:'अवलोकन',tasks:'काम',money:'पैसे',documents:'दस्तावेज़',home:'घर और चीज़ें',settings:'सेटिंग्स',greet:'नमस्ते'},bn:{overview:'পর্যালোচনা',tasks:'কাজ',money:'অর্থ',documents:'নথি',home:'বাড়ি ও জিনিস',settings:'সেটিংস',greet:'নমস্কার'}};
function save(){localStorage.setItem('haven-preferences',JSON.stringify(prefs));localStorage.setItem('haven-tasks',JSON.stringify(tasks));}
function applyPrefs(){document.body.dataset.theme=prefs.theme;document.documentElement.lang=prefs.language;const t=translations[prefs.language];$('#profileName').textContent=prefs.name;$('#avatarLetter').textContent=prefs.name.slice(0,1).toUpperCase();$('#greeting').textContent=`${t.greet}, ${prefs.name}`;$('#settingName').value=prefs.name;$('#settingLanguage').value=prefs.language;$('#remindersToggle').checked=prefs.reminders;$('#settingsBtn').innerHTML=`⚙ ${t.settings}`;$$('.nav-item').forEach(n=>{const label=n.dataset.page;const text={dashboard:t.overview,tasks:t.tasks,money:t.money,documents:t.documents,home:t.home}[label];const textNode=[...n.childNodes].find(node=>node.nodeType===Node.TEXT_NODE);if(textNode)textNode.nodeValue=' '+text+' ';});$$('.theme-options button').forEach(b=>b.classList.toggle('selected',b.dataset.theme===prefs.theme));$('#welcomeScreen').classList.toggle('hide',prefs.onboarded);}
function render(){
 $('#timeline').innerHTML=timeline.map(x=>`<div class="timeline-item ${x[3]||''}"><div class="timeline-date">${x[0]}</div><div class="timeline-line"></div><div class="timeline-content"><strong>${x[1]}</strong><span>${x[2]}</span></div></div>`).join('');
 $('#nudgeList').innerHTML=tasks.filter(t=>!t.done).slice(0,3).map((t,i)=>`<div class="nudge"><div class="nudge-icon">${['⌑','✚','◉'][i]}</div><div><strong>${t.name}</strong><span>${t.meta}</span></div><button class="complete-nudge" data-i="${tasks.indexOf(t)}">✓</button></div>`).join('');
 $('#allTasks').innerHTML=tasks.map((t,i)=>`<div class="task-row ${t.done?'done':''}"><input class="task-check" data-i="${i}" type="checkbox" ${t.done?'checked':''}><div class="task-info"><strong>${t.name}</strong><span>${t.meta}</span></div><span class="tag ${t.urgent?'urgent':''}">${t.tag}</span></div>`).join('');
 $('#billsList').innerHTML=bills.map(b=>`<div class="bill-row"><div class="bill-logo">${b[0]}</div><div class="bill-info"><strong>${b[1]}</strong><span>${b[2]}</span></div><div class="bill-amount"><strong>${b[3]}</strong><span>Upcoming</span></div></div>`).join('');
 $('#documentGrid').innerHTML=docs.map(d=>`<article class="document-card"><div class="big-doc-icon">${d[0]}</div><h3>${d[1]}</h3><p>${d[2]}</p><span class="status">● ${d[3]}</span></article>`).join('');
 $('#homeGrid').innerHTML=home.map(h=>`<article class="home-item"><div class="home-symbol">${h[0]}</div><h3>${h[1]}</h3><p>${h[2]}</p><span class="service">${h[3]}</span></article>`).join('');
 $('#taskBadge').textContent=tasks.filter(t=>!t.done).length;$('#doneCount').textContent=tasks.filter(t=>t.done).length+2;
 $$('.task-check').forEach(c=>c.onchange=e=>{tasks[e.target.dataset.i].done=e.target.checked;save();render();toast(e.target.checked?'Nice — marked complete.':'Moved back to your list.');});$$('.complete-nudge').forEach(b=>b.onclick=()=>{tasks[b.dataset.i].done=true;save();render();toast('Marked complete — nicely done.');});
}
function openPage(id){$$('.page').forEach(p=>p.classList.toggle('active-page',p.id===id));$$('.nav-item').forEach(n=>n.classList.toggle('active',n.dataset.page===id));window.scrollTo(0,0);$('.sidebar').classList.remove('open');}
function toast(t){const el=$('#toast');el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2600);}
$$('.nav-item').forEach(n=>n.onclick=e=>{e.preventDefault();openPage(n.dataset.page);});$$('[data-go]').forEach(b=>b.onclick=()=>openPage(b.dataset.go));
const modal=$('#modalBackdrop');function openModal(title){$('#modalTitle').textContent=title;modal.classList.add('show');$('#entryName').focus();}function closeModal(){modal.classList.remove('show');}
['addBtn','newTaskBtn','newBillBtn','uploadBtn','newItemBtn'].forEach(id=>$('#'+id).onclick=()=>openModal(id==='newTaskBtn'?'New task':'Add something'));$('#focusTaskBtn').onclick=()=>{openPage('tasks');toast('Your insurance reminder is already waiting.');};$('.close-modal').onclick=closeModal;modal.onclick=e=>{if(e.target===modal)closeModal();};$('#entryForm').onsubmit=e=>{e.preventDefault();tasks.unshift({name:$('#entryName').value,meta:$('#entryDate').value+' · Personal',tag:'New'});save();render();closeModal();openPage('tasks');e.target.reset();toast('Saved to your Haven.');};
$('.mobile-menu').onclick=()=>$('.sidebar').classList.toggle('open');$('#searchBtn').onclick=()=>{openPage('tasks');toast('Tip: use Haven AI to find your next step.');};$('#notifyBtn').onclick=()=>toast(`You have ${tasks.filter(t=>!t.done).length} things that need attention.`);
const settings=$('#settingsBackdrop');function openSettings(){applyPrefs();settings.classList.add('show');}function closeSettings(){settings.classList.remove('show');}$('#settingsBtn').onclick=openSettings;$('#profileBtn').onclick=openSettings;$('.close-settings').onclick=closeSettings;settings.onclick=e=>{if(e.target===settings)closeSettings();};$$('.theme-options button').forEach(b=>b.onclick=()=>{prefs.theme=b.dataset.theme;applyPrefs();});$('#saveSettings').onclick=()=>{prefs.name=$('#settingName').value.trim()||'Friend';prefs.language=$('#settingLanguage').value;prefs.reminders=$('#remindersToggle').checked;save();applyPrefs();closeSettings();toast('Your Haven has been personalised.');};
$('#welcomeForm').onsubmit=e=>{e.preventDefault();prefs.name=$('#welcomeName').value.trim()||'Friend';prefs.language=$('#welcomeLanguage').value;prefs.onboarded=true;save();applyPrefs();toast(`Welcome to Haven, ${prefs.name}.`);};
const ai=$('#aiPanel');$('#aiFab').onclick=()=>ai.classList.toggle('open');$('#closeAi').onclick=()=>ai.classList.remove('open');function aiReply(q){const s=q.toLowerCase();if(s.includes('week')||s.includes('plan'))return 'A gentle plan: renew car insurance, book your dental visit, then review Netflix. Three small wins, one at a time.';if(s.includes('money')||s.includes('save')||s.includes('bill'))return 'You have ₹9,600 coming up. Start with your electricity bill today, then check whether your Netflix plan still suits you.';if(s.includes('attention')||s.includes('urgent'))return `Your clearest next action is car insurance. It expires in 8 days, and you have ${tasks.filter(t=>!t.done).length} open tasks.`;return 'I can help you choose a next step. Try asking “What needs attention?” or “Plan my week.”';}function addMessage(text,who='ai'){const el=document.createElement('div');el.className=who==='user'?'user-message':'ai-message';el.textContent=text;$('#aiMessages').appendChild(el);$('#aiMessages').scrollTop=9999;}$('#aiForm').onsubmit=e=>{e.preventDefault();const q=$('#aiInput').value.trim();if(!q)return;addMessage(q,'user');$('#aiInput').value='';setTimeout(()=>addMessage(aiReply(q)),380);};$$('.ai-suggestions button').forEach(b=>b.onclick=()=>{addMessage(b.textContent,'user');setTimeout(()=>addMessage(aiReply(b.textContent)),300);});
const now=new Date();$('#todayDate').textContent=now.toLocaleDateString('en-IN',{weekday:'long',day:'numeric',month:'long'});applyPrefs();render();
